/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#002265",
        "primary-container": "#003594",
        "on-primary": "#ffffff",
        "on-primary-container": "#87a4ff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#15409e",
        "inverse-primary": "#b4c5ff",
        secondary: "#a04100",
        "secondary-container": "#fe6b00",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#572000",
        "secondary-fixed": "#ffdbcc",
        "secondary-fixed-dim": "#ffb693",
        "on-secondary-fixed": "#351000",
        "on-secondary-fixed-variant": "#7a3000",
        tertiary: "#002f01",
        "tertiary-container": "#004802",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4ebe42",
        "tertiary-fixed": "#8afc77",
        "tertiary-fixed-dim": "#6edf5e",
        "on-tertiary-fixed": "#002201",
        "on-tertiary-fixed-variant": "#005303",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#f5faff",
        "on-background": "#111d24",
        surface: "#f5faff",
        "surface-dim": "#cfdce5",
        "surface-bright": "#f5faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e9f5ff",
        "surface-container": "#e3f0f9",
        "surface-container-high": "#ddeaf4",
        "surface-container-highest": "#d7e4ee",
        "surface-variant": "#d7e4ee",
        "surface-tint": "#3559b7",
        "on-surface": "#111d24",
        "on-surface-variant": "#444652",
        "inverse-surface": "#263239",
        "inverse-on-surface": "#e6f3fc",
        outline: "#747683",
        "outline-variant": "#c4c6d4",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0 32px 64px -12px rgba(17,29,36,0.06)",
        float: "0 8px 32px -4px rgba(17,29,36,0.08)",
        card: "0 2px 16px -2px rgba(17,29,36,0.05)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-in-right": "slideInRight 0.3s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideInRight: {
          "0%": { transform: "translateX(20px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};


